from google.auth.crypt import base

RSA_KEY_MODULE_PREFIX: str

class RSAVerifier(base.Verifier):
    def __init__(self, public_key: object) -> None: ...
    def verify(self, message: object, signature: object) -> bool: ...
    @classmethod
    def from_string(cls, public_key: object) -> RSAVerifier: ...

class RSASigner(base.Signer, base.FromServiceAccountMixin):
    def __init__(
        self, private_key: object, key_id: str | None = None
    ) -> None: ...
    @property
    def key_id(self) -> str: ...
    def sign(self, message: object) -> bytes: ...
    @classmethod
    def from_string(
        cls, key: object, key_id: str | None = None
    ) -> RSASigner: ...
