CRYPTOGRAPHY_NOT_FOUND_ERROR: str

def get_agent_identity_certificate_path() -> str | None: ...
def get_and_parse_agent_identity_certificate() -> object | None: ...
def parse_certificate(cert_bytes: bytes) -> object: ...
def calculate_certificate_fingerprint(cert: object) -> str: ...
def should_request_bound_token(cert: object) -> bool: ...
def get_cached_cert_fingerprint(cached_cert: bytes | None) -> str: ...
