from collections.abc import Hashable
from typing import TypeVar, overload

_Key = TypeVar("_Key", bound=Hashable)
_Value = TypeVar("_Value")
_T = TypeVar("_T")

class LRUCache(dict[_Key, _Value]):
    maxsize: int

    def __init__(self, maxsize: int) -> None: ...
    def clear(self) -> None: ...
    def __getitem__(self, key: _Key) -> _Value: ...
    def __setitem__(self, key: _Key, value: _Value) -> None: ...
    def __delitem__(self, key: _Key) -> None: ...
    def popitem(self) -> tuple[_Key, _Value]: ...
    def _update(self, key: _Key) -> None: ...
    @overload
    def get(self, key: _Key, default: None = ...) -> _Value | None: ...
    @overload
    def get(self, key: _Key, default: _Value) -> _Value: ...
    @overload
    def get(self, key: _Key, default: _T) -> _Value | _T: ...
