import threading

class RefreshThreadManager:
    def __init__(self) -> None: ...
    def start_refresh(self, cred: object, request: object) -> bool: ...
    def clear_error(self) -> None: ...

class RefreshThread(threading.Thread):
    def __init__(
        self, cred: object, request: object, **kwargs: object
    ) -> None: ...
    def run(self) -> None: ...
